import "@/app/globals.css";

import { dir } from "i18next";
import { languages } from "../i18n/settings";

import SupabaseProvider from "./SupabaseProvider";
import { createServerComponentSupabaseClient } from "@supabase/auth-helpers-nextjs";
import { cookies, headers } from "next/headers";
import { useState } from "react";

export const metadata = {
  title: "ImmobileLink",
  description: "Generated by create next app",
};

interface RootLayout {
  children: any;
  params: { lang: string };
}

export async function generateStaticParams() {
  return languages.map((lang) => ({ lang }));
}

export async function generateSupabaseSession() {
  const supabase = createServerComponentSupabaseClient({
    headers,
    cookies,
  });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return { session };
}

export default async function RootLayout({
  children,
  params: { lang },
}: RootLayout) {
  return (
    <html
      lang={lang}
      dir={dir(lang)}
    >
      <body>
        <SupabaseProvider session={null}>{children}</SupabaseProvider>
      </body>
    </html>
  );
}
